### ISSUE TITLE
[feat] 최근 달성 미션 10개 조회 API 구현

### ISSUE THREAD

**Issue by jiaeYoon** [Da-gather/Dagather-Backend#29]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 사용자 개인 페이지에서 완료한 미션 중 최근에 달성한 미션 10개 조회

## 📋 TODO
- [x] API 구현

**Comment by jiaeYoon** [comment]
- [ ] response body에 id, friendId, friendImageUrl 추가
