### ISSUE TITLE
[fix] 친구 신청 목록 조회 API 수정

### ISSUE THREAD

**Issue by Lightieey** [Da-gather/Dagather-Backend#43]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 설명을 작성해주세요

## 📋 TODO
- [ ] response body에 상대방 memberid, name, image url만 가도록 수정
