### ISSUE TITLE
[fix] mission complete API 변수 자료형 수정

### ISSUE THREAD

**Issue by jiaeYoon** [Da-gather/Dagather-Backend#49]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- memberId 변수의 자료형을 Integer에서 String으로 수정함

## 📋 TODO
- [x] memberId 관련 변수(memberId, memberId1, memberId2)의 자료형 변경
