### ISSUE TITLE
[fix] friend response areWeFriend 수정

### ISSUE THREAD

**Issue by Lightieey** [Da-gather/Dagather-Backend#51]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- friend response areWeFriend 수정

## 📋 TODO
- [ ] friend response areWeFriend 수정
