### ISSUE TITLE
[fix] authfilter 오류

### ISSUE THREAD

**Issue by Lightieey** [Da-gather/Dagather-Backend#58]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- authfilter 삭제하고 타겟 API에서 @RequestHeader로 받는걸로 수정

## 📋 TODO
- [ ] /profile/list?filter=
- [ ] /friend/list
- [ ] /friend/list/:requestBy
- [ ] authFilter 삭제
