### ISSUE TITLE
[fix] 진행 중인 미션 조회, 최근 달성 10개 미션 조회 API 수정

### ISSUE THREAD

**Issue by jiaeYoon** [Da-gather/Dagather-Backend#60]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- response body 수정

## 📋 TODO
- [x] 진행중인 미션 조회 : response body에 id, friendId, friendImageUrl 추가, completedAt 삭제
- [x] 최근 달성 10개 미션 조회 : response body에 id, friendId, friendImageUrl 추가

**Comment by jiaeYoon** [comment]
- [ ] response body에 사용자 이름 추가
