### ISSUE TITLE
[feat] 채팅방 진행 미션 조회 API 구현, 완료 미션 목록 조회 API 수정

### ISSUE THREAD

**Issue by jiaeYoon** [Da-gather/Dagather-Backend#63]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 1:1 채팅방에서 진행중인 미션을 보여주는 API 구현
- 1:1 채팅방에서 완료한 미션 목록을 보여주는 API 수정

## 📋 TODO
- [x] 채팅방 진행 미션 조회 API 구현
- [x] 완료 미션 목록 조회 API의 response body 수정(+id, friendId, friendName, friendImageUrl)
