### ISSUE TITLE
[fix] 프로필 저장 및 수정 API 수정

### ISSUE THREAD

**Issue by Lightieey** [Da-gather/Dagather-Backend#76]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 프로필 저장 및 수정 API 수정

## 📋 TODO
- [ ] multipart/form -> application/json으로 수정
- [ ] 모든 필드 string으로 받던거 각각 타입 맞게 바꾸기 (int, boolean, float 등)
